version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      frontend-dependencies:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: monthly
    groups:
      rust-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
